### ISSUE TITLE
没有发布到 jetbrain 的 plugin 仓库里吗

### ISSUE THREAD

**Issue by aristotll** [enbandari/NewDataClassAction#1]
![2017-07-03 08 26 11](https://user-images.githubusercontent.com/13341544/27774689-5ef4bfda-5fc9-11e7-8f27-2cbc35dd2014.png)

**Comment by starktonys** [comment]
+10086 赶紧提交到 plugin仓库 或者，请求原作者加上对Kotlin的支持

**Comment by bennyhuo** [comment]
审核需要时间哈~

**Comment by bennyhuo** [comment]
先在github下载本地安装吧

**Comment by bennyhuo** [comment]
https://github.com/enbandari/NewDataClassAction/tree/master/distributions
